### ISSUE TITLE
On the Joint method

### ISSUE THREAD

**Issue by MiaoyunZhao** [aimagelab/mammoth#1]
Hi, thanks for the code base, I want to use it in my work. However, I met a problem when I run the joint method. If I am not misunderstanding, It looks like the "observe" function is not defined correctly. Could you please help with it? Thanks.

**Comment by mbosc** [comment]
Hi @MiaoyunZhao,

You have found a bug in our joint training that only affects Seq-MNIST (CIFAR and other datasets were fine). We pushed an update: if you pull now everything should work.

Also, the bug was not in the observe function of joint.py. That function does nothing because the JOINT method does not handle examples as they are presented by the continual learning dataloaders. Instead, it only fits the entire i.i.d. dataset at the end of the last task (see function end_task of joint.py).
