### ISSUE TITLE
Hyperparameter for CIFAR-10 on X-DER

### ISSUE THREAD

**Issue by coyoteling** [aimagelab/mammoth#34]
Hi,
  Recently we are reproducing the code you provided, have you now found a suitable hyperparameter for CIFAR-10 on X-DER? If you find it, could you please reply?

Thank you very much!

**Comment by loribonna** [comment]
Hi @coyoteling , we still haven't done a thorough search on CIFAR-10 as we have focused on bigger/longer datasets. 
I will update this issue if we find the time/resources to do it properly.

**Comment by loribonna** [comment]
Ok I managed to run some experiments on CIFAR-10 and here are my results.
I followed the setting of [X-DER](https://arxiv.org/abs/2201.00766) (`batch_size=minibatch_size=32`, lr scheduler with milestones at 35 and 45 epochs and `0.2` gamma reduction, `50` epochs) and run both *X-DER* and *X-DER w. RPC*, comparing with `DER++`.

Here are my results:
- X-DER: 71.39 (alpha=0.3`, `beta=1`, `lambd=0.05`, `eta=0.01`, `m=0.5`, `simclr_num_aug=4`, `lr=0.03`).
- X-DER w. RPC: 73.02 (alpha=0.3`, `beta=0.8`, `eta=0.01`, `m=0.5`, `lr=0.03`).
- DER++: 72.86 (`alpha=0.3`, `beta=0.8`, `lr=0.03`).

Regardless of the results, it seems that X-DER becomes less effective on CIFAR-10, which I'm guessing to be due to the smaller number of tasks that do not allow the SimCLR regularization of X-DER to make a tangible contribution.

SimCLR also influences the length of the experiments: X-DER takes around 5 times more time than both DER++ and X-DER w. RPC. If we were to make X-DER today we would probably use a more efficient SSL regularization such as Barlow Twins.
