### ISSUE TITLE
[Model Error]: SLCA fc is None

### ISSUE THREAD

**Issue by M1andy** [aimagelab/mammoth#46]
# SLCA model seems to forget to initialize it's fc module.

model: `SLCA`
dataset: `seq-cifar100-224`

## ENVIRONMENT:
- python=3.10.14
- torch=2.2.0+cu121
- torchvision=0.17.0+cu121

## REPRODUCE:
1. clean install requirements.txt
2. using the command below to run experiment.

```bash
python --model=slca \
       --dataset=seq-cifar100-224 \
       --num_workers=4  \ 
       --memory_size=1000 \
       --memory_per_class=10 \
       --lr=1e-3 \
       --n_epochs=1 \
       --eval_epochs=1 \
       --enable_other_metrices=1
```

## ERROR MESSAGE:
```bash
'NoneType' object is not callable
  File "/sharefiles4/name/projects/name/er/models/slca_utils/inc_net.py", line 135, in forward
    out = self.fc(x)
  File "/sharefiles4/name/projects/name/er/models/slca.py", line 104, in forward
    logits = self.net._network(x)['logits']
  File "/sharefiles4/name/projects/name/er/utils/training.py", line 93, in evaluate
    outputs = model(inputs)
  File "/sharefiles4/name/projects/name/er/utils/training.py", line 257, in train
    random_results_class, random_results_task = evaluate(model, dataset_copy)
  File "/sharefiles4/name/projects/name/er/utils/main.py", line 268, in main
    train(model, dataset, args)
  File "/sharefiles4/name/projects/name/er/utils/main.py", line 272, in <module>
    main()
TypeError: 'NoneType' object is not callable
```

**Comment by loribonna** [comment]
Hi @M1andy , thanks for the detailed error description. 

The issue is with the `--enable_other_metrics` flag which needs to evaluate the model at the beginning of all tasks to compute the forward and backward transfer.  This happens before the `begin_task` is called, during which `slca` initializes the classifier.

I would recommend not using the `--enable_other_metrics=1` flag at the moment since its implementation is quite outdated and needs some care (and tests) to function properly.

**Comment by M1andy** [comment]
> Hi @M1andy , thanks for the detailed error description.
> 
> The issue is with the `--enable_other_metrics` flag which needs to evaluate the model at the beginning of all tasks to compute the forward and backward transfer. This happens before the `begin_task` is called, during which `slca` initializes the classifier.
> 
> I would recommend not using the `--enable_other_metrics=1` flag at the moment since its implementation is quite outdated and needs some care (and tests) to function properly.


Thank you for the solution. It seems a little bit weird to evaluate before all the tasks begin, since you haven't **LEARNED** things. I would like to leave the issue opened as it is not solved yet. 

By the way, this project is awesome! 👍

**Comment by M1andy** [comment]
I think I get what you mean. The old-fashion continual learning methods such as lwf, which use a plain random initialize feature extractor, always has a ZERO accuracy before training. So there is no need to evaluate before training, we just assume that the first task forward transfer is equal to the first task's evaluation accuracy. However, there is a trend recently that using large pretrained model for continual learning, which results in the high accuracy before all the continual tasks. 
For a fair comparison, now we need to evaluate the model before continual training, because the method using pretrained model has a higher forward transfer if we still assume that the model has zero accuracy before training.

**Comment by loribonna** [comment]
Yes you are mostly correct. However I don't think that just having a pretrained models will lead you to have higher accuracy since the classifier is always re-initialized (as the classes change from those of the pre-train). 
Instead, models that are based on CLIP will have some zero-shot capabilities on unseen classes and may be evaluated before continual training.
